language: python
sudo: false
dist: trusty
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: 2.6
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: "3.5-dev"
    - python: "nightly"
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
    - cmake
    - build-essential
    - python-dev
    - bluetooth
    - libbluetooth-dev
    - libboost-python-dev
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install sphinx sphinx_rtd_theme"
  - "pip install -r requirements.txt"
  - "pip install -e ."
script: py.test tests/ --cov pymetawear --cov-report term-missing
env:
  global:
    - GH_REF: github.com/hbldh/pymetawear.git
deploy:
  provider: script
  script: deploy_gh_pages.sh
  on:
    branch: master

