language: generic
sudo: required
dist: trusty
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"
  - "nightly"
matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: "3.5-dev"
    - python: "nightly"
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
    - cmake
    - build-essential
    - libglib2.0-dev
    - python-dev
    - bluez
    - bluetooth
    - libbluetooth-dev
    - libboost-python-dev
    - libboost-thread-dev
install:
  - "sudo pip install pytest"
  - "sudo pip install pytest-cov"
  - "sudo pip install python-coveralls"
  - "sudo pip install Sphinx sphinx_rtd_theme"
  - "sudo pip install -e ."
script: py.test tests/ --cov pymetawear --cov-report term-missing
after_success:
  - coveralls
env:
  global:
    - GH_REF: github.com/hbldh/pymetawear.git
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy_gh_pages.sh
  on:
    branch: master
    python: 2.7
